### ISSUE TITLE
Rylie from SCU

### ISSUE THREAD

**Issue by seato66** [matt-bowles/clocker.in#1]
Surely you remember me from doing our Uni major together (clocker in) 
This is not an issue for clocker.in ;) please email me as we are looking for a PHP dev where I work, seato66@gmail.com. 
Thanks!! @matt-bowles

**Comment by matt-bowles** [comment]
@seato66 Hey mate, thanks heaps for letting me know about this, but unfortunately I'm already working elsewhere. Totally appreciate it and would have 100% jumped on it if I was not already employed. All the best.
